-- V5: Update Branch table and Create Casbin policy tables

-- ============================================================================
-- 1. UPDATE BRANCHES TABLE (table already exists from V2)
-- ============================================================================
-- Add missing columns to existing branches table
ALTER TABLE branches ADD COLUMN IF NOT EXISTS description VARCHAR(1000);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS organization_id UUID;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS parent_id UUID;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 0;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS path VARCHAR(500);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS manager_id UUID;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;

-- Add soft delete columns (required by SoftDeletableEntity)
ALTER TABLE branches ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(100);

-- Add tenant_id column (required by TenantAwareAggregateRoot)
ALTER TABLE branches ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255) NOT NULL DEFAULT 'default';

-- Fix audit columns type mismatch (entity expects VARCHAR, V2 created UUID)
ALTER TABLE branches ALTER COLUMN created_by VARCHAR(100);
ALTER TABLE branches ALTER COLUMN updated_by VARCHAR(100);

-- Add indexes if they don't exist (H2 will skip if exists)
CREATE INDEX IF NOT EXISTS idx_branch_org_id ON branches(organization_id);
CREATE INDEX IF NOT EXISTS idx_branch_parent_id ON branches(parent_id);
CREATE INDEX IF NOT EXISTS idx_branch_code ON branches(code);
CREATE INDEX IF NOT EXISTS idx_branch_deleted_id ON branches(deleted, id);
CREATE INDEX IF NOT EXISTS idx_branch_status ON branches(status);
CREATE INDEX IF NOT EXISTS idx_branch_tenant_id ON branches(tenant_id);

-- Add foreign key constraints (H2 will error if exists, so we try-catch via IF NOT EXISTS)
-- Note: H2 doesn't support IF NOT EXISTS for constraints, so we comment these out
-- ALTER TABLE branches ADD CONSTRAINT IF NOT EXISTS fk_branch_organization FOREIGN KEY (organization_id) REFERENCES organizations(id);
-- ALTER TABLE branches ADD CONSTRAINT IF NOT EXISTS fk_branch_parent FOREIGN KEY (parent_id) REFERENCES branches(id);

-- ============================================================================
-- 2. ADD BRANCH_ID AND DATA_SCOPE TO USERS TABLE
-- ============================================================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS branch_id UUID;
ALTER TABLE users ADD COLUMN IF NOT EXISTS data_scope VARCHAR(20) NOT NULL DEFAULT 'SELF_ONLY';

CREATE INDEX IF NOT EXISTS idx_user_branch_id ON users(branch_id);
CREATE INDEX IF NOT EXISTS idx_user_data_scope ON users(data_scope);

ALTER TABLE users ADD CONSTRAINT fk_user_branch
    FOREIGN KEY (branch_id) REFERENCES branches(id);

-- ============================================================================
-- 3. CREATE CASBIN POLICY TABLE
-- ============================================================================
-- Casbin policy table theo cấu trúc của jCasbin JDBC Adapter
CREATE TABLE IF NOT EXISTS casbin_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype VARCHAR(100) NOT NULL,  -- p (policy), g (grouping), g2 (role hierarchy)
    v0 VARCHAR(100),              -- subject (user/role)
    v1 VARCHAR(100),              -- domain (tenant)
    v2 VARCHAR(100),              -- object (resource)
    v3 VARCHAR(100),              -- action
    v4 VARCHAR(100),              -- effect (allow/deny)
    v5 VARCHAR(100)               -- scope (optional)
);

-- Indexes for casbin_rule
CREATE INDEX idx_casbin_rule_ptype ON casbin_rule(ptype);
CREATE INDEX idx_casbin_rule_v0 ON casbin_rule(v0);
CREATE INDEX idx_casbin_rule_v1 ON casbin_rule(v1);
CREATE INDEX idx_casbin_rule_v0_v1 ON casbin_rule(v0, v1);

-- ============================================================================
-- 4. INSERT DEFAULT DATA
-- ============================================================================

-- Insert default branch cho các organizations đã có
INSERT INTO branches (id, code, name, organization_id, level, path, branch_type, status, tenant_id, created_by)
SELECT
    RANDOM_UUID(),
    'HQ',
    org.name || ' - Head Quarter',
    org.id,
    0,
    '/HQ',
    'HQ',
    'ACTIVE',
    CAST(org.id AS VARCHAR),
    'system'
FROM organizations org
WHERE NOT EXISTS (
    SELECT 1 FROM branches b WHERE b.organization_id = org.id
);

-- Insert default Casbin policies for ADMIN role
INSERT INTO casbin_rule (ptype, v0, v1, v2, v3, v4) VALUES
    -- ROLE_ADMIN có quyền truy cập tất cả APIs
    ('p', 'ROLE_ADMIN', 'default', '/api/.*', '(GET)|(POST)|(PUT)|(DELETE)', 'allow'),

    -- ROLE_MANAGER có quyền đọc và tạo
    ('p', 'ROLE_MANAGER', 'default', '/api/.*', '(GET)|(POST)', 'allow'),

    -- ROLE_ORC có quyền đọc trong phạm vi branch
    ('p', 'ROLE_ORC', 'default', '/api/.*', 'GET', 'allow'),

    -- ROLE_MAKER có quyền tạo và đọc bản ghi của mình
    ('p', 'ROLE_MAKER', 'default', '/api/.*/create', 'POST', 'allow'),
    ('p', 'ROLE_MAKER', 'default', '/api/.*/mine', 'GET', 'allow'),

    -- ROLE_CHECKER có quyền xem và approve
    ('p', 'ROLE_CHECKER', 'default', '/api/.*/approve', 'POST', 'allow'),
    ('p', 'ROLE_CHECKER', 'default', '/api/.*/pending', 'GET', 'allow'),

    -- ROLE_USER có quyền đọc cơ bản
    ('p', 'ROLE_USER', 'default', '/api/users/me', 'GET', 'allow'),
    ('p', 'ROLE_USER', 'default', '/api/organizations', 'GET', 'allow');
